// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwV23lOt_mv3jeCHvmpDtLSRKiikzCPs',
    appId: '1:200650453484:web:1b97b519cd047913a3d0c9',
    messagingSenderId: '200650453484',
    projectId: 'qubits-b4228',
    authDomain: 'qubits-b4228.firebaseapp.com',
    storageBucket: 'qubits-b4228.firebasestorage.app',
    measurementId: 'G-L8KGPLX0C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahUhQTqOgikrFdXyp4Clv-4pN7J345kY',
    appId: '1:200650453484:android:9f69e8d5efb9dcb2a3d0c9',
    messagingSenderId: '200650453484',
    projectId: 'qubits-b4228',
    storageBucket: 'qubits-b4228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXd0VKM093Yku7AcHwzttwy-X38AV4Pw',
    appId: '1:200650453484:ios:50f7fe787c043e88a3d0c9',
    messagingSenderId: '200650453484',
    projectId: 'qubits-b4228',
    storageBucket: 'qubits-b4228.firebasestorage.app',
    iosBundleId: 'com.example.qubits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwXd0VKM093Yku7AcHwzttwy-X38AV4Pw',
    appId: '1:200650453484:ios:50f7fe787c043e88a3d0c9',
    messagingSenderId: '200650453484',
    projectId: 'qubits-b4228',
    storageBucket: 'qubits-b4228.firebasestorage.app',
    iosBundleId: 'com.example.qubits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjwV23lOt_mv3jeCHvmpDtLSRKiikzCPs',
    appId: '1:200650453484:web:c1b895f888f5b790a3d0c9',
    messagingSenderId: '200650453484',
    projectId: 'qubits-b4228',
    authDomain: 'qubits-b4228.firebaseapp.com',
    storageBucket: 'qubits-b4228.firebasestorage.app',
    measurementId: 'G-1LYSRBHK0M',
  );

}